### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by JoyMonteiro** [lmtm/prez#5]
Hello,

How do I add fragments in my markdown file?
I know reveal.js has some support for fragments
https://github.com/hakimel/reveal.js#element-attributes

but I'm very new to Javascripts, and I don't how to get the markdown parser to convert my
text into something like that.

TIA,
Joy

**Comment by Delapouite** [comment]
Hi Joy.

reveal.js parses markdown in 2 distinct phases : 
-  one dedicated to classic markdown grammar with **marked**
- [a custom one](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js) handles special comments in the source, like the ones you need to trigger fragments navigation.

Unfortunately, prez only currently takes care of the marked parsing. We'll have a look on how to parse comments properly.

**Comment by JoyMonteiro** [comment]
Oh, ok. Thanks, and look forward to it!

**Comment by xnum** [comment]
@Delapouite I found this issue and try to deal with it,
I forked a marked repo and change the lexer grammar
https://github.com/x000032001/marked/commit/0b859c9afd3242d57414a82afa25a16119135c09
then I use __ surround to set strings with fragment
and add `$class:fragment class$` on slides' heading

but I think it's not a good solution, do you have any advice on it?

**Comment by Delapouite** [comment]
The problem about Reveal.js custom comments adding property to markdown is that this is currently done in the DOM itself : https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js#L312-L345

Prez does not compile markdown in the browser but in node, so we do not have access to the DOM. One solution could be to extract all the logic from the script aforementioned and run it in a cheerio environment but it would be really hacky.

My best advice therefore when you want to extend so much the markdown syntax, to use fragments for instance, is to simply fallback on normal HTML since it's legal syntax. This way, no need to learn a half-baked DSL.

**Comment by naholyr** [comment]
In order to be able to extend Markdown's syntax you can now use the parser of your choice. Example, using a CLI markdown converter:

``` js
// your-project/my-markdown-parser.js
const spawnSync = require("child_process").spawnSync
module.exports = (input) => spawnSync("maruku", { input }).stdout.toString("utf8")
```

``` ini
// your-project/.prezrc
parser = ./my-markdown-parser
```
